### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by nirs** [open-cluster-management-io/governance-policy-framework-addon#12]
The readme explains how to build and install from git. I want to install 
a released version, as part of ramen test environment.

Currently we install the old archived components:
https://github.com/RamenDR/ramen/blob/6924acd0689d5ad320598fe8f0a38be169db575a/hack/ocm-minikube.sh#L770

Adding minimal instructions in the readme would be nice.

**Comment by dhaiducek** [comment]
@nirs Sorry we missed this issue! Do the instructions from the documentation website answer your question? They instruct how to deploy `v0.9.0`:
https://open-cluster-management.io/getting-started/integration/policy-framework/#deploy-from-source

**Comment by nirs** [comment]
@dhaiducek yes, I found https://open-cluster-management.io/getting-started and use clusteradm to install everything. I think this can be resolved by linking to the getting started docs in the readme.

For reference, here is how we install this component now in ramen:
- managed cluster: https://github.com/RamenDR/ramen/blob/9a71d28f342f47ce9b1bbeaea976962f5409c1fb/test/ocm-cluster/start#L12
- hub: https://github.com/RamenDR/ramen/blob/9a71d28f342f47ce9b1bbeaea976962f5409c1fb/test/ocm-hub/start#L12

clusteradm does most of the hard work, but it does not support `--wait` for `install hub-addon` or for `addon enable`, so we have to keep list of deployments and wait for them, which is fragile in case deployment is removed or added behind our back.

I guess I should open an issue about this for clusteradm.

**Comment by dhaiducek** [comment]
Good point--we can update our README to link to these docs.

Yes, `--wait` would be an issue for `clusteradm`, but I don't think it'd be a very large effort since it's implemented elsewhere and hopefully the same code could be leveraged for the addon commands.
